/*
 * This source file was generated by the Gradle 'init' task
 */
package com.bat;

public class App {
    public String getGreeting() {
        return "lo ";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
