/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    // Source: https://mvnrepository.com/artifact/com.mysql/mysql-connector-j
    implementation("com.mysql:mysql-connector-j:9.5.0")
    implementation ("com.formdev:flatlaf:3.7")
    implementation("com.formdev:flatlaf-extras:3.7")
    implementation("com.formdev:flatlaf-fonts-roboto:2.137")
    implementation ("com.toedter:jcalendar:1.4")
    implementation ("org.apache.poi:poi:5.2.5")
    implementation ("org.apache.poi:poi-ooxml:5.2.5")
    implementation("com.itextpdf:itextpdf:5.5.13.3")
}



    // Source: https://mvnrepository.com/artifact/org.apache.pdfbox/pdfbox
    //implementation("org.apache.pdfbox:pdfbox:3.0.6")
    

// Apply a specific Java toolchain to ease working on different environments.

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
    // optional: set source/target compatibility to ensure bytecode level
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
application {
    mainClass = "com.bat.GUI.Main"

    if (hasProperty("launch")) {
        mainClass.set("${property("launch")}")
    }
    // Define the main class for the application.
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
